version: '3'
services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile 
    restart: unless-stopped
    volumes:
      - ../../../webroot:/var/www/html

  nginx:
    container_name: nginx
    build: 
      context: ./build/nginx
    volumes:
      - ../../../webroot:/var/www/html
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/sites/:/etc/nginx/sites-available
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8001:80
      - 8002:81
      - 8003:83
      #- 443:443
    depends_on:
      - php-fpm
    restart: always

