FROM php:7.2-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install libpq-dev libpng-dev locales -y

# Set the locale
RUN sed -i -e 's/# fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG fr_FR.UTF-8  
ENV LANGUAGE fr_FR:fr  
ENV LC_ALL fr_FR.UTF-8

RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql pgsql gd

